4. DB/1111(django 팔로잉까지 완료)/accounts/urls.py
from django.urls import path

# . : 현재 디렉토리리
from . import views

# {% url namespace:name %}
# app_name = 'namespace'
app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name = 'login'),
    path('logout/', views.logout, name = 'logout'),
    path('signup/', views.signup, name = 'signup'), # 회원가입
    # request : 이미 로그인 되어있는 user의 데이터
    path('delete/', views.delete, name = 'delete'), # 회원탈퇴
    path('update/', views.update, name = 'update'), # 회원정보변경
    path('profile/<username>/', views.profile, name = 'profile'), # 개인 프로필
    path('<int:user_pk>/follow/', views.follow, name = 'follow'), # 팔로잉 했을때
]

4. DB/1111(django 팔로잉까지 완료)/accounts/models.py
from django.db import models

# Create your models here.

# AbstractUser : 자동으로 필드를 제공(로그인, 권한 관리 등)
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    # symmetrical=False
    # 내가 상대를 팔로잉했다고 상대가 나를 팔로우 한건 아니다.
    followings = models.ManyToManyField(
        'self', symmetrical=False, related_name='followers'
    )

4. DB/1111(django 팔로잉까지 완료)/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import get_user_model

# from .models import User
# 직접 참조

# 간접 참조
# get_user_model ---> 커스텀 User 모델을 자동을 변환
# User 모델을 변경하더라도 폼을 수정할 필요가 없다.

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        # model = User # 직접 참조
        model = get_user_model() # 간접참조

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        # 모든 필드가 다 조회
        model = get_user_model()
        # 정보 변경할 필드만 가져오기
        fields = ('first_name', 'last_name', 'email')

4. DB/1111(django 팔로잉까지 완료)/accounts/views.py
from django.shortcuts import render, redirect

# Create your views here.

# articles -> model form
# accounts -> built-in form

from django.contrib.auth.forms import (
    AuthenticationForm, # 로그인을 위한 폼 bult-in form
    UserCreationForm, # 회원가입(db 저장.번경) - model form
    PasswordChangeForm, # 비밀번호 변경 bult-in form
)

from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from .models import User


from django.contrib.auth.decorators import login_required

def login(request):
    # 아이디와 패스워드 입력하고 로그인 버튼(submit)버튼 눌렀을 때
    if request.method == 'POST':
        # request.POST : 아이디, 비밀번호
        # request : user <--- AuthenticationMiddleware
        form = AuthenticationForm(request, request.POST)
        # 유효성 검사
        if form.is_valid():
            # get_user() : 인증된 사용자의 객체
            # signup(회원가입)과 차이 ---> 이미 DB에 존재하는 사용자를 인증
            auth_login(request, form.get_user())
            return redirect('articles:index')
    
    # ---------------------------------------------------------------------------

    # 로그인 버튼(submit) 누르기 전
    else:
        form = AuthenticationForm() # 빈 폼

    # GET요청 or 유효성 검사 실패
    context = {
        'form' : form # 빈 폼
    }
    
    return render(request, 'accounts/login.html', context)

# 로그인을 한 사용자만 로그아웃을 할 수 있다.
@login_required
def logout(request):
    auth_logout(request)
    return redirect('articles:index')

from .forms import CustomUserCreationForm, CustomUserChangeForm

def signup(request):
    # 이미 존재하는 회원
    if request.user.is_authenticated:
        return redirect('articles:index')

    # 새로 회원가입(submit 버튼 눌렀을때)
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid(): # 1. 유효성 검사
            user = form.save() # 2. DB에 저장
            auth_login(request, user) # 3. 로그인
            return redirect('articles:index')
    else: # submit 버튼 누르기 전
        form = CustomUserCreationForm() # 빈폼
    # 유효성검사 실패
    context = {
        'form' : form
    }
    return render(request, 'accounts/signup.html', context)

@login_required
def delete(request):
    # request.user : 현재 로그인 되어있는 user
    request.user.delete()
    return redirect('articles:index')

@login_required
def update(request):
    # submit버튼 눌렀을 때
    if request.method == 'POST':
        # request.POST : 회원 정보에 입력한 수정사항
        form = CustomUserChangeForm(request.POST, instance = request.user)
        # 유효성검사
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    
    else: # submit 버튼 누르기 전
        form = CustomUserChangeForm(instance = request.user)
    # 유효성검사 실패 or GET 요청
    context = {
        'form' : form
    }
    return render(request, 'accounts/update.html', context)

from django.contrib.auth import update_session_auth_hash

@login_required
def change_password(request, user_pk):
    # 비밀번호 변경 버튼 눌렀을 떄
    if request.method == 'POST':
        # 왜 request.user 먼저 나올까?
        # 부모클래스인 SetPasswordForm의 생성자 함수 첫번째 인자가 user
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            # 비밀번호 변경하고 로그인 유지할지 안할지
            update_session_auth_hash(request, user)
            # 로그인 유지하고 리다이렉트
            return redirect('articles:index')
    else:
        form = PasswordChangeForm(request.user) # 빈폼 X (현재 로그인한 사용자)
    
    context = {
        'form' : form
    }
    return render(request, 'accounts/change_password.html', context)

from django.contrib.auth import get_user_model

def profile(request, username):
    User = get_user_model()
    # person -> 로그인한 사용자? X
    person = User.objects.get(username=username)
    # 유저 정보를 페이지에 넘겨서 프로필 페이지 만드려고
    context = {
        'person': person
    }
    return render(request, 'accounts/profile.html', context)

@login_required
def follow(request, user_pk):
    User = get_user_model()
    # person : user_pk가 팔로우 하려는 상대방
    person = User.objects.get(pk=user_pk)
    # 자기자신 팔로우하는것 방지
    if person != request.user:
        # filter.exists() : DB에 존재하는지 확인 -> True / False
        # 팔로잉을 이미 했는지 안했는지
        if person.followers.filter(pk=request.user.pk).exists():
            # 팔로우 취소
            person.followers.remove(request.user)
        else:
            # 팔로잉
            person.followers.add(request.user)

    return redirect('accounts:profile', person.username)

4. DB/1111(django 팔로잉까지 완료)/accounts/templates/accounts/change_password.html
{% extends "base.html" %}


{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url "change_password" user.pk %}" method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="비밀번호 변경">
</form>

{% endblock content %}

4. DB/1111(django 팔로잉까지 완료)/accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block content %}
  <h1>로그인</h1>
  <form action="{% url "accounts:login" %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit">
  </form>
{% endblock content %}

4. DB/1111(django 팔로잉까지 완료)/accounts/templates/accounts/profile.html
{% extends "base.html" %}


{% block content %}
  <h1> {{person.username}} 님의 프로필 </h1>
  
  <hr>

  <div>
    <div>
      팔로잉 : {{person.followings.all|length}}
      / 팔로워 : {{person.followers.all|length}}
    </div>
    {% comment %} request.user : 로그인한 사용자, person : 프로필 페이지 소유자 {% endcomment %}
    {% if request.user != person %}
      <form action="{% url "accounts:follow" person.pk %}" method="POST">
        {% csrf_token %}
        {% if request.user in person.followers.all %}
          <input type="submit" value="언팔로우">
        {% else %}
          <input type="submit" value="팔로우">
        {% endif %}
      </form>
    {% endif %}
  </div>


  <hr>
  <h2>게시글</h2>
  {% comment %} 외래키가 article에 있으니까 person이 article을 가져오려면 역참조 {% endcomment %}
  {% for article in person.article_set.all %}
    <div>{{article.title}}</div>
  {% endfor %}

  <hr>
  <h2>댓글</h2>
  {% comment %} 역참조 {% endcomment %}
  {% for comment in person.comment_set.all %}
    <div>{{comment.content}}</div>
  {% endfor %}

  <hr>
  <h2>좋아요한 게시글</h2>
  {% for article in person.like_articles.all %}
    <div>{{article.title}}</div>
  {% endfor %}


{% endblock content %}

4. DB/1111(django 팔로잉까지 완료)/accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block content %}
<h1>회원가입</h1>

<form action="{% url "accounts:signup" %}" method = "POST">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" value="회원가입">
</form>

{% endblock content %}

4. DB/1111(django 팔로잉까지 완료)/accounts/templates/accounts/update.html
{% extends "base.html" %}


{% block content %}
<h1>회원 정보 수정</h1>
<form action="{% url "accounts:update" %}" method = 'POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="정보수정">
</form>


{% endblock content %}